version: '3'

services: 
    frontend:
        build: ./frontend
        ports: 
            - "4000:3000"
        container_name: pokedex-docker
        restart: always
        links:
            - backend
    backend:
        build: ./backend
        ports:
            - "8000:8080"
        container_name: pokeserver-docker
        restart: always